# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk:
  - openjdk11
mvn:
  -B package

services:
 - postgresql

before_install:
 - psql -c 'create database tracker;' -U postgres
 - psql -c 'create database users;' -U postgres
 - psql -c 'create database spring_carsell;' -U postgres
 - psql -c 'create database cinema;' -U postgres



# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - dreamhunter1@ukr.net
    on_success: never # default: change
    on_failure: always # default: always
